---
- hosts: tag_aws_autoscaling_groupName_ansible_asg_test
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: check apt last update
      apt: update_cache=yes cache_valid_time=3600
      
  roles:
    -  web
