
apache_port_http: 80

apache_create_vhosts: true

apache_conf_path: "/etc/apache2/sites-available/"

file_name: "index.htm"

host_path: "/etc/hosts"

apache_vhosts:

- {servername: "prod.rolindroy.com", documentroot: "/var/www/html/prod.rolindroy.com"}
